#FROM instruction is first instruction in docker file, it represents base OS
#File name should be Dockerfile
# RHEL-9 is VM linux OS with high memory, its not a opensource, will go with alma linux 
FROM almalinux:9   